export type {
  Apiario,
  ApiarioView,
  Arnia,
  ArniaModelloId,
  ArniaStato,
  ArniaView,
  Foto,
  Produzione,
  Regina,
  ReginaColoreInternazionale,
  ReginaOrigineTipo,
  ReginaStatoOperativo,
  Trattamento,
  TrattamentoCalendarioPromemoria,
  Visita,
  GiroApiario,
  GiroApiarioStato,
} from './entities'

export type {
  ApiarioInput,
  ApiarioUpdate,
  ArniaInput,
  ArniaUpdate,
  CreateApiarioData,
  CreateArniaData,
  FotoInput,
  FotoUpdate,
  ProduzioneInput,
  ProduzioneUpdate,
  SmielaturaInput,
  ReginaInput,
  ReginaUpdate,
  TrattamentoInput,
  TrattamentoUpdate,
  VisitaInput,
  VisitaUpdate,
  GiroApiarioInput,
  GiroApiarioUpdate,
} from './inputs'
