export type {
  Apiario,
  ApiarioView,
  Arnia,
  ArniaModelloId,
  ArniaStato,
  ArniaView,
  Foto,
  Produzione,
  Regina,
  Trattamento,
  Visita,
} from './entities'

export type {
  ApiarioInput,
  ApiarioUpdate,
  ArniaInput,
  ArniaUpdate,
  CreateApiarioData,
  CreateArniaData,
  FotoInput,
  FotoUpdate,
  ProduzioneInput,
  ProduzioneUpdate,
  ReginaInput,
  ReginaUpdate,
  TrattamentoInput,
  TrattamentoUpdate,
  VisitaInput,
  VisitaUpdate,
} from './inputs'
